Prueba_IIP/Controllers/EstudiantesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Prueba_IIP.Model;
using Prueba_IIP.Model.TableViewModel;
using Prueba_IIP.Model.ViewModel;


namespace Prueba_IIP.Controllers
{
    public class EstudiantesController : Controller
    {
        // GET: Estudiantes
        public ActionResult Index()
        {
            List<EstudiantesTableViewModel> lstestudiante = null;
            using(var db= new db_prueba_IIPEntities())
            {
                lstestudiante = (from v in db.Estudiantes
                                 join m in db.Grupo on v.idGrupo equals m.idGrupo
                                 select new EstudiantesTableViewModel
                                 {
                                     IdEstudiante = v.idEstudiante,
                                     Nombre=v.Nombre,
                                     Apellido=v.Apellido,
                                     nombGrupo=m.nombreGrupo
                                 }).ToList();
            }
            return View(lstestudiante);
            
        }
        public void CargarCboxMarcas()
        {
            List<SelectListItem> list = null;
            using (var db = new db_prueba_IIPEntities())
            {
                list = (from m in db.Grupo
                        select new SelectListItem
                        {
                            Value = m.idGrupo.ToString(),
                            Text = m.nombreGrupo.ToString()
                        }).ToList();
                ViewBag.marcas = list;
            }
        }
        public ActionResult Nuevo()
        {
            CargarCboxMarcas();
            return View();
        }

        [HttpPost]
        public ActionResult Nuevo(EstudianteViewModel model)
        {
            if (!ModelState.IsValid)
            {
                CargarCboxMarcas();
                return View(model);
            }

            using (db_prueba_IIPEntities db = new db_prueba_IIPEntities())
            {
                Estudiantes oVehiculo = new Estudiantes();
                oVehiculo.Nombre = model.Nombre;
                oVehiculo.Apellido = model.Apellido;
                oVehiculo.idGrupo = model.idGrupo;
                db.Estudiantes.Add(oVehiculo);
                db.SaveChanges();
            }
            return Redirect(Url.Content("~/Estudiantes/"));
        }

        public ActionResult Edit(int id)
        {
            CargarCboxMarcas();
            EditarEstudianteViewModel model = new EditarEstudianteViewModel();

            using (var db = new db_prueba_IIPEntities())
            {
                var oMarca = db.Estudiantes.Find(id);
                model.Id = oMarca.idEstudiante;
                model.nombre = oMarca.Nombre;
                model.apellido = oMarca.Apellido;
                model.idGrupo = oMarca.idGrupo;

            }
            return View(model);
        }

        // POST: Estudiantes/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EditarEstudianteViewModel model)
        {
            if (!ModelState.IsValid)
            {
                CargarCboxMarcas();
                return View(model);
            }

            using (db_prueba_IIPEntities db = new db_prueba_IIPEntities())
            {
                var oVehiculo = db.Estudiantes.Find(model.Id);
                oVehiculo.Nombre = model.nombre;
                oVehiculo.Apellido = model.apellido;
                oVehiculo.idGrupo = model.idGrupo;
                //oVehiculo.Grupo = db.Grupo.Find(model.idGrupo);

                db.Entry(oVehiculo).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }
            return Redirect(Url.Content("~/Estudiantes/"));

        }

        public ActionResult Eliminar(int id)
        {
            EliminarEstudianteViewModel model = new EliminarEstudianteViewModel();

            using (var db = new db_prueba_IIPEntities())
            {
                var oVehiculo = db.Estudiantes.Find(id);
                db.Estudiantes.Remove(oVehiculo);
                db.SaveChanges();
            }
            return Redirect(Url.Content("~/Estudiantes/"));
        }


    }
}

Prueba_IIP/Views/Estudiantes/Edit.cshtml
@model Prueba_IIP.Model.ViewModel.EditarEstudianteViewModel
@{
    ViewBag.Title = "Edit";
    List<SelectListItem> listaMarcas = (List<SelectListItem>)ViewBag.marcas;
}

<h2>Edit</h2>

<div class="row">
    <div class="col-12">
        @using (Html.BeginForm("Edit", "Estudiantes", FormMethod.Post, new { role = "form", }))
        {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(d => d.Id);
        @Html.LabelFor(d => d.nombre, new { @class = "form-content" })
        @Html.TextBoxFor(d => d.nombre, new { @class = "form-control" })
        @Html.LabelFor(d => d.apellido, new { @class = "form-content" })
        @Html.TextBoxFor(d => d.apellido, new { @class = "form-control" })
        @Html.LabelFor(d => d.nombGrupo, new { @class = "form-content" })
        @Html.DropDownList("idGrupo", listaMarcas, null, new { @class = "form-control" })
        <br />

        <div style="text-align:left;">
            <input type="submit" class="btn btn-success" value="Guardar" />
        </div>
    }
    </div>
</div>

Prueba_IIP/Views/Estudiantes/Index.cshtml
@model List<Prueba_IIP.Model.TableViewModel.EstudiantesTableViewModel>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@Html.ActionLink("Nuevo", "Nuevo", "Estudiantes", new { }, new { @class = "btn btn-primary" })
<table>
    <tr>
        <th>ID</th>
        <th>Nombre</th>
        <th>Apellido</th>
        <th>Grupo</th>
    </tr>
    @foreach (var estudiante in Model)
    {
<tr>
    <td>@estudiante.IdEstudiante</td>
    <td>@estudiante.Nombre</td>
    <td>@estudiante.Apellido</td>
    <td>@estudiante.nombGrupo</td>
    <td>
        <button class="btn btn-warning"  onclick="document.location.href = '@Url.Content("~/Estudiantes/Edit/"+@estudiante.IdEstudiante)' ">Editar</button>
    </td>
    <td>
        <button class="btn btn-danger" onclick="document.location.href = '@Url.Content("~/Estudiantes/Eliminar/"+@estudiante.IdEstudiante)' ">Eliminar</button>
    </td>
</tr>
    }
</table>

Prueba_IIP/Views/Estudiantes/Nuevo.cshtml
@model Prueba_IIP.Model.ViewModel.EstudianteViewModel
@{
    ViewBag.Title = "Nuevo";
    List<SelectListItem> listaMarcas = (List<SelectListItem>)ViewBag.marcas;
}

<h2>Nuevo</h2>


<div>
    <div>
        @using (Html.BeginForm("Nuevo", "Estudiantes", FormMethod.Post, new { role = "form" }))
        {
            @Html.AntiForgeryToken()
            @Html.LabelFor(d => d.Nombre, new { @class = "form-content" })
            @Html.TextBoxFor(d => d.Nombre, new { @class = "form-control" })
            @Html.LabelFor(d => d.Apellido, new { @class = "form-content" })
            @Html.TextBoxFor(d => d.Apellido, new { @class = "form-control" })
            @Html.LabelFor(d => d.nombGrupo, new { @class = "form-content" })
            @Html.DropDownList("idGrupo", listaMarcas, null, new { @class = "form-control" })
            <br />

            <div style="text-align:left;">
                <input type="submit" class="btn btn-success" value="Guardar" />
            </div>
        }
    </div>
</div>