Prueba_IIP/Controllers/GrupoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Prueba_IIP.Model;
using Prueba_IIP.Model.TableViewModel;
using Prueba_IIP.Model.ViewModel;
namespace Prueba_IIP.Controllers
{
    public class GrupoController : Controller
    {
        // GET: Grupo
        public ActionResult Index()
        {
            List<GrupoTableViewModel> list = null;
            using (db_prueba_IIPEntities db = new db_prueba_IIPEntities())
            {
                list = (from d in db.Grupo
                        select new GrupoTableViewModel
                        {
                            idGrupo=d.idGrupo,
                            nombreGrupo=d.nombreGrupo

                        }
                       ).ToList();
            }
            return View(list);
        }
        [HttpGet]
        public ActionResult Nuevo()
        {

            return View();
        }
        public ActionResult Nuevo(GrupoViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            using (db_prueba_IIPEntities db = new db_prueba_IIPEntities())
            {
                Grupo oMarca = new Grupo();
                //oMarca.idGrupo = model.Id;
                oMarca.nombreGrupo = model.NombreGrupo;
                db.Grupo.Add(oMarca);
                db.SaveChanges();
            }
            return Redirect(Url.Content("~/Grupo/"));
        }
        public ActionResult Eliminar(int id)
        {
            EliminarGrupoViewModel model = new EliminarGrupoViewModel();

            using (var db = new db_prueba_IIPEntities())
            {
                var oMarca = db.Grupo.Find(id);
                db.Grupo.Remove(oMarca);
                db.SaveChanges();
            }
            return Redirect(Url.Content("~/Grupo/"));
        }
        public ActionResult Editar(int id)
        {
            EditarGrupoViewModel model = new EditarGrupoViewModel();

            using (var db = new db_prueba_IIPEntities())
            {
                var oMarca = db.Grupo.Find(id);
                model.Id = oMarca.idGrupo;
                model.NombreGrupo = oMarca.nombreGrupo;
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Editar(EditarGrupoViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            using (db_prueba_IIPEntities db = new db_prueba_IIPEntities())
            {
                var oMarca = db.Grupo.Find(model.Id);
                oMarca.nombreGrupo = model.NombreGrupo;

                db.Entry(oMarca).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }
            return Redirect(Url.Content("~/Grupo/"));
        }
    }
}

Prueba_IIP/Views/Grupo/Editar.cshtml
@model Prueba_IIP.Model.ViewModel.EditarGrupoViewModel
@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>

<div class="row">
    <div class="col-12">
        @using (Html.BeginForm("Editar", "Grupo", FormMethod.Post, new { role = "form", }))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(d => d.Id);
            @Html.LabelFor(d => d.NombreGrupo, new { @class = "form-content" })
            @Html.TextBoxFor(d => d.NombreGrupo, new { @class = "form-control" })

            <br />

            <div style="text-align left;">
                <input type="submit" class="btn btn-primary" value="Guardar">
            </div>
        }
    </div>
</div>

Prueba_IIP/Views/Grupo/Index.cshtml
@model List<Prueba_IIP.Model.TableViewModel.GrupoTableViewModel>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@Html.ActionLink("Nuevo", "Nuevo", "Grupo", new { }, new { @class = "btn btn-primary" })
<div class="row">
    <div class="col-lg-5">
        <table class="table table-bordered">
            <tr>
                <td>
                    ID
                </td>
                <td>
                    Descripcion
                </td>
                <td>
                </td>
                <td>
                </td>
            </tr>
            @foreach (var oMarca in Model)
            {
                <tr>
                    <td>
                        @oMarca.idGrupo
                    </td>
                    <td>
                        @oMarca.nombreGrupo
                    </td>
                    <td>
                        <button class="btn btn-warning" onclick="document.location.href = '@Url.Content("~/Grupo/Editar/"+@oMarca.idGrupo)' ">Editar</button>
                    </td>
                    <td>
                        <button class="btn btn-danger" onclick="document.location.href = '@Url.Content("~/Grupo/Eliminar/"+@oMarca.idGrupo)' ">Eliminar</button>
                    </td>
                </tr>
       }
        </table>
    </div>
</div>

Prueba_IIP/Views/Grupo/Nuevo.cshtml
@model Prueba_IIP.Model.ViewModel.GrupoViewModel
@{
    ViewBag.Title = "Nuevo";
}

<h2>Nuevo</h2>
<div>
    <div>
        @using (Html.BeginForm("Nuevo", "Grupo", FormMethod.Post, new { role = "form" }))
        {
            @Html.AntiForgeryToken()
            @Html.LabelFor(d => d.NombreGrupo, new { @class = "form-content" })
            @Html.TextBoxFor(d => d.NombreGrupo, new { @class = "form-control" })
            <br />

            <div style="text-align:left;">
                <input type="submit" class="btn btn-success" value="Guardar" />
            </div>
        }
    </div>
</div>